version: "3.9"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mydata:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
volumes:
  mydata:
    driver: local
