version: "3.9"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mydata:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/usr/src/ooca-app/uploads
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8080:8080"
    volumes:
      - ./document:/usr/share/nginx/html/document
    environment:
      URLS_PRIMARY_NAME: "OOCA-APP"
      URLS: "[{ url: 'document/api.yaml', name: 'Occa app API'},]"
volumes:
  mydata:
    driver: local
